# Generated by Django 5.0 on 2023-12-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_Code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Event_Name', models.CharField(max_length=255)),
                ('Event_Status', models.BooleanField()),
                ('Event_Start', models.DateTimeField()),
                ('Event_End', models.DateTimeField()),
                ('Tagged_Temple_Goshala_Code', models.CharField(choices=[('T', 'T'), ('G', 'G')], default='T', max_length=50)),
                ('Tagged_Code', models.CharField(max_length=50)),
                ('Tagged_Geo_Site', models.CharField(max_length=255)),
                ('Location_Code', models.CharField(max_length=50)),
                ('Event_Map_Location', models.CharField(max_length=255)),
                ('Event_Contact_Name', models.CharField(max_length=255)),
                ('Event_Contact_Phone', models.CharField(max_length=20)),
                ('Event_Email', models.EmailField(max_length=255)),
                ('Event_Image_FileName1', models.FileField(blank=True, upload_to='static/media/event_images/')),
                ('Event_Image_FileName2', models.FileField(blank=True, null=True, upload_to='static/media/event_images/')),
                ('Event_Image_FilePath1', models.FileField(blank=True, null=True, upload_to='static/media/event_images/')),
                ('Event_Image_FilePath2', models.FileField(blank=True, null=True, upload_to='static/media/event_images/')),
                ('Event_URL_Link1', models.URLField(blank=True, max_length=255, null=True)),
                ('Event_URL_Link2', models.URLField(blank=True, max_length=255, null=True)),
                ('Event_Desc', models.TextField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event_Category',
            fields=[
                ('Event_Category_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Event_Category_Name', models.CharField(max_length=100)),
                ('Event_Category_Desc', models.TextField()),
            ],
            options={
                'db_table': 'event_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goshala_category',
            fields=[
                ('Goshala_Category_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Goshala_Category_Name', models.CharField(max_length=100)),
                ('Goshala_Category_Desc', models.TextField()),
            ],
            options={
                'db_table': 'goshala_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goshala_Model',
            fields=[
                ('Goshala_Code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Goshala_Name', models.CharField(max_length=255)),
                ('Goshala_Regn_No', models.CharField(max_length=50)),
                ('Goshala_Status', models.BooleanField()),
                ('Tagged_Geo_Site', models.CharField(max_length=255)),
                ('Location_Code', models.CharField(max_length=50)),
                ('Goshala_Map_Location', models.CharField(max_length=255)),
                ('Goshala_Image_FilePath1', models.FileField(blank=True, null=True, upload_to='static/media/goshala_images/')),
                ('Goshala_Image_FilePath2', models.FileField(blank=True, null=True, upload_to='static/media/goshala_images/')),
                ('Goshala_URL_Link1', models.URLField(blank=True, max_length=255, null=True)),
                ('Goshala_URL_Link2', models.URLField(blank=True, max_length=255, null=True)),
                ('Goshala_Contact_Name', models.CharField(max_length=255)),
                ('Goshala_Contact_Phone', models.CharField(max_length=20)),
                ('Goshala_Address', models.TextField()),
                ('Goshala_Email', models.EmailField(max_length=255)),
                ('Goshala_Desc', models.TextField()),
                ('Goshal_Regn_Document', models.FileField(upload_to='static/media/goshala_documents/')),
            ],
            options={
                'db_table': 'goshala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('Temple_Code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Temple_Name', models.CharField(max_length=100)),
                ('Yr_of_Con', models.IntegerField(blank=True, null=True)),
                ('Era', models.CharField(max_length=50)),
                ('Is_Temp_Dest', models.BooleanField()),
                ('Temple_Anim_Sacri_Status', models.BooleanField()),
                ('Temple_Diety', models.BooleanField()),
                ('Temple_Style', models.CharField(choices=[('_', '_'), ('N', 'N'), ('D', 'D'), ('V', 'V')], default='_', max_length=50)),
                ('Tagged_Geo_Site', models.CharField(max_length=100)),
                ('Location_Code', models.CharField(max_length=10)),
                ('Temple_Map_Location', models.CharField(max_length=100)),
                ('Temple_Address', models.TextField()),
                ('Temple_Image_FileName1', models.FileField(upload_to='static/media/temple_images/')),
                ('Temple_Image_FileName2', models.FileField(upload_to='static/media/temple_images/')),
                ('Temple_Image_FilePath1', models.FileField(upload_to='static/media/temple_images/')),
                ('Temple_Image_FilePath2', models.FileField(upload_to='static/media/temple_images/')),
                ('Temple_URL_Link1', models.URLField()),
                ('Temple_URL_Link2', models.URLField()),
                ('Temple_Contact_Name', models.CharField(max_length=100)),
                ('Temple_Contact_Phone', models.CharField(max_length=15)),
                ('Temple_Email', models.EmailField(max_length=254)),
                ('Temple_Desc', models.TextField()),
            ],
            options={
                'db_table': 'temple',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temple_category',
            fields=[
                ('Temple_Category_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Temple_Category_Name', models.CharField(max_length=100)),
                ('Temple_Category_Desc', models.TextField()),
            ],
            options={
                'db_table': 'temple_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temple_priority',
            fields=[
                ('Temple_priority_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Temple_priority_Name', models.CharField(max_length=100)),
                ('Temple_priority_Desc', models.TextField()),
            ],
            options={
                'db_table': 'temple_priority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='templePriority',
            fields=[
                ('Temple_priority_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Temple_priority_Name', models.CharField(max_length=100)),
                ('Temple_priority_Desc', models.TextField()),
            ],
            options={
                'db_table': 'temple_priority',
                'managed': False,
            },
        ),
    ]
