# Generated by Django 5.0 on 2024-01-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temple_priority',
        ),
    ]
