# Generated by Django 5.0 on 2023-12-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationtree', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country_ap',
        ),
    ]
